# Generated by Django 2.1.5 on 2020-09-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterField(
            model_name='history',
            name='viewed_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
